### ISSUE TITLE
Vercel link does not work

### ISSUE THREAD

**Issue by nounder** [HoudiniGraphql/intro#16]
https://pokedex-gray-two.vercel.app/ returns 404

**Comment by AlecAivazis** [comment]
👋 

Where did you see that link?

**Comment by nounder** [comment]
Just below this repo's "About" section: https://github.com/HoudiniGraphql/intro

**Comment by AlecAivazis** [comment]
For me, the readme points to https://houdini-intro.pages.dev/ which is working. Can you take a screenshot of the link you see so I can make sure I"m following?
