### ISSUE TITLE
Demo pokedex-gray-two.vercel.app doesn't work

### ISSUE THREAD

**Issue by frederikhors** [HoudiniGraphql/intro#5]
Demo https://pokedex-gray-two.vercel.app/ doesn't work.

**Comment by AlecAivazis** [comment]
Thanks for the heads up @frederikhors! I'll get this fixed ASAP

**Comment by AlecAivazis** [comment]
This is now running at https://houdini-intro.pages.dev/ using the `1.0` prerelease 🥳
