### ISSUE TITLE
Duplicate apollo-server dependency

### ISSUE THREAD

**Issue by vanor89** [HoudiniGraphql/intro#6]
Package json contains `apollo-server` dependency under both `dependencies` and `devDependencies`.

I tried making a Pull Request but was not allowed to create my own branch. Let me know if theres anything I can do to help!

**Comment by AlecAivazis** [comment]
Thanks for offering to fix it! Sorry I didn't see this sooner, I wasn't watching the repo for some reason I missed the notification.

I'll fix this ASAP
