### ISSUE TITLE
Conflicting project dependencies

### ISSUE THREAD

**Issue by romelperez** [HoudiniGraphql/intro#9]
## Environment

- Hardware: Apple Mac M1
- OS: Big Sur
- Node.js: 18.12
- NPM: 8.19.2

## Use Case

I downloaded the project as it is [in the documentation](https://www.houdinigraphql.com/intro/welcome):

```bash
npx degit houdinigraphql/intro hello-houdini
cd hello-houdini
```

But when I try to install the dependencies with:

```bash
npm install
```

I get this error:

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: houdini-intro@0.0.1
npm ERR! Found: graphql@15.7.2
npm ERR! node_modules/graphql
npm ERR!   graphql@"15.7.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^16.2.0" from graphql-relay@0.10.0
npm ERR! node_modules/graphql-relay
npm ERR!   graphql-relay@"^0.10.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

## Expected Result

The dependencies should be installed successfully.

**Comment by AlecAivazis** [comment]
Thanks for reporting this @romelperez - i just pulled everything down and fixed a few of these issues that were popping up. Mind confirming for me?

**Comment by romelperez** [comment]
Now it installs properly in the `main` branch. Though the `final` branch still remains the same. Thank you @AlecAivazis!
